server.port=8000

# College Shared Oracle Database Configuration
spring.datasource.url=jdbc:oracle:thin:@172.16.100.12:1521:orcl
spring.datasource.username=p717824161
spring.datasource.password=p717824161
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# HikariCP Connection Pool Configs
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000

# JSON Formatting
spring.jackson.serialization.indent-output=true
