server.port=8083
spring.application.name=company-service

# Local MySQL Workbench Database Connection
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/internmatch_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.initialization-fail-timeout=0
spring.datasource.hikari.connection-timeout=1500

# JWT Secret
jwt.secret=${JWT_SECRET:InternMatchSuperSecretKeyForJWTTokenGeneration2026SecureKeyWith256BitsLength}

# Frontend Origin
frontend.origin=${FRONTEND_ORIGIN:http://localhost:5173}
