package com.internmatch.auth.config;

import org.springframework.boot.CommandLineRunner;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
public class DatabaseInitializer implements CommandLineRunner {

    private final JdbcTemplate jdbcTemplate;

    public DatabaseInitializer(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @Override
    public void run(String... args) {
        try {
            // Create users table
            jdbcTemplate.execute("CREATE TABLE users (" +
                    "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "username VARCHAR2(100) UNIQUE, " +
                    "name VARCHAR2(200), " +
                    "email VARCHAR2(200) UNIQUE, " +
                    "password VARCHAR2(200), " +
                    "role VARCHAR2(50), " +
                    "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
        } catch (Exception e) {}

        try {
            // Create student_profiles table
            jdbcTemplate.execute("CREATE TABLE student_profiles (" +
                    "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "user_id NUMBER UNIQUE, " +
                    "name VARCHAR2(200), " +
                    "college VARCHAR2(200), " +
                    "degree VARCHAR2(100), " +
                    "branch VARCHAR2(100), " +
                    "year_of_study VARCHAR2(50), " +
                    "cgpa NUMBER(4,2), " +
                    "grad_year NUMBER(4), " +
                    "skills VARCHAR2(500), " +
                    "phone VARCHAR2(50), " +
                    "address VARCHAR2(300), " +
                    "dob VARCHAR2(50), " +
                    "gender VARCHAR2(50), " +
                    "leetcode VARCHAR2(100), " +
                    "github VARCHAR2(100), " +
                    "linkedin VARCHAR2(300), " +
                    "portfolio VARCHAR2(300), " +
                    "bio VARCHAR2(1000), " +
                    "resume_file_name VARCHAR2(200), " +
                    "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
        } catch (Exception e) {}

        try {
            // Create companies table
            jdbcTemplate.execute("CREATE TABLE companies (" +
                    "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "user_id NUMBER UNIQUE, " +
                    "company_name VARCHAR2(200), " +
                    "industry VARCHAR2(200), " +
                    "website VARCHAR2(300), " +
                    "location VARCHAR2(200), " +
                    "description VARCHAR2(1000), " +
                    "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
        } catch (Exception e) {}

        try {
            // Seed initial admin, student, and company users
            jdbcTemplate.update("MERGE INTO users u USING (SELECT 'thilakvignesh' as username FROM dual) d " +
                    "ON (u.username = d.username) " +
                    "WHEN NOT MATCHED THEN INSERT (username, name, email, password, role) VALUES ('thilakvignesh', 'Thilak Vignesh (Admin)', 'thilakvignesh@gmail.com', 'ThilakVignesh', 'ADMIN')");

            jdbcTemplate.update("MERGE INTO users u USING (SELECT 'demo1@gmail.com' as username FROM dual) d " +
                    "ON (u.username = d.username) " +
                    "WHEN NOT MATCHED THEN INSERT (username, name, email, password, role) VALUES ('demo1@gmail.com', 'Vignesh Sankarakumar', 'demo1@gmail.com', '123456', 'STUDENT')");

            jdbcTemplate.update("MERGE INTO users u USING (SELECT 'thilak' as username FROM dual) d " +
                    "ON (u.username = d.username) " +
                    "WHEN NOT MATCHED THEN INSERT (username, name, email, password, role) VALUES ('thilak', 'Thilak P', 'thilak@gmail.com', '123456', 'STUDENT')");

            jdbcTemplate.update("MERGE INTO users u USING (SELECT 'nvidia' as username FROM dual) d " +
                    "ON (u.username = d.username) " +
                    "WHEN NOT MATCHED THEN INSERT (username, name, email, password, role) VALUES ('nvidia', 'NVIDIA Corporation', 'nvidia@gmail.com', '123456', 'COMPANY')");
        } catch (Exception e) {}
    }
}
