-- Flyway Database Migration: V1__init_schema.sql
-- Unified Oracle Database Schema for InternMatch AI

CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100) NOT NULL UNIQUE,
    name VARCHAR2(200),
    email VARCHAR2(200) NOT NULL UNIQUE,
    password VARCHAR2(200) NOT NULL,
    role VARCHAR2(50) NOT NULL,
    phone VARCHAR2(50),
    gender VARCHAR2(50),
    dob VARCHAR2(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE student_profiles (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL UNIQUE,
    name VARCHAR2(200),
    college VARCHAR2(200),
    degree VARCHAR2(100),
    branch VARCHAR2(100),
    year_of_study VARCHAR2(50),
    cgpa NUMBER(4,2),
    grad_year NUMBER(4),
    skills VARCHAR2(500),
    phone VARCHAR2(50),
    address VARCHAR2(300),
    dob VARCHAR2(50),
    gender VARCHAR2(50),
    leetcode VARCHAR2(100),
    github VARCHAR2(100),
    linkedin VARCHAR2(300),
    portfolio VARCHAR2(300),
    bio VARCHAR2(1000),
    resume_file_name VARCHAR2(200),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_student_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE companies (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL UNIQUE,
    company_name VARCHAR2(200) NOT NULL,
    industry VARCHAR2(200),
    website VARCHAR2(300),
    location VARCHAR2(200),
    description VARCHAR2(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_company_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE internships (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id NUMBER NOT NULL,
    company_name VARCHAR2(200),
    title VARCHAR2(200) NOT NULL,
    domain VARCHAR2(100),
    required_skills VARCHAR2(500),
    work_mode VARCHAR2(50) DEFAULT 'Hybrid',
    grad_year NUMBER(4),
    location VARCHAR2(100),
    duration VARCHAR2(50),
    start_date VARCHAR2(50),
    end_date VARCHAR2(50),
    stipend NUMBER(10,2) DEFAULT 0,
    openings NUMBER(4) DEFAULT 1,
    application_deadline VARCHAR2(50),
    status VARCHAR2(50) DEFAULT 'ACTIVE',
    is_active NUMBER(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE applications (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id NUMBER NOT NULL,
    internship_id NUMBER NOT NULL,
    company_id NUMBER,
    student_name VARCHAR2(200),
    company_name VARCHAR2(200),
    role_title VARCHAR2(200),
    test_score NUMBER(5,2) DEFAULT 0,
    proctor_warnings NUMBER(4) DEFAULT 0,
    status VARCHAR2(50) DEFAULT 'APPLIED',
    stage VARCHAR2(50) DEFAULT 'ASSESSMENT',
    match_score NUMBER(5,2) DEFAULT 0,
    applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_student_internship UNIQUE (student_id, internship_id)
);

CREATE TABLE notifications (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    title VARCHAR2(200) NOT NULL,
    message VARCHAR2(1000) NOT NULL,
    type VARCHAR2(50) DEFAULT 'SYSTEM',
    is_read NUMBER(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE screening_tests (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    internship_id NUMBER NOT NULL UNIQUE,
    title VARCHAR2(200) NOT NULL,
    passing_score NUMBER(5,2) DEFAULT 60,
    duration_minutes NUMBER(4) DEFAULT 45,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
