package com.internmatch.company.config;

import org.springframework.boot.CommandLineRunner;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
public class DatabaseInitializer implements CommandLineRunner {

    private final JdbcTemplate jdbcTemplate;

    public DatabaseInitializer(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @Override
    public void run(String... args) {
        try {
            // Create internships table
            jdbcTemplate.execute("CREATE TABLE internships (" +
                    "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "company_id NUMBER, " +
                    "company_name VARCHAR2(200), " +
                    "title VARCHAR2(200), " +
                    "domain VARCHAR2(100), " +
                    "required_skills VARCHAR2(500), " +
                    "work_mode VARCHAR2(50), " +
                    "grad_year NUMBER(4), " +
                    "location VARCHAR2(100), " +
                    "duration VARCHAR2(50), " +
                    "start_date VARCHAR2(50), " +
                    "end_date VARCHAR2(50), " +
                    "stipend NUMBER(10,2), " +
                    "openings NUMBER(4), " +
                    "application_deadline VARCHAR2(50), " +
                    "status VARCHAR2(50) DEFAULT 'ACTIVE', " +
                    "is_active NUMBER(1) DEFAULT 1, " +
                    "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
        } catch (Exception e) {}

        try {
            // Create applications table
            jdbcTemplate.execute("CREATE TABLE applications (" +
                    "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "student_id NUMBER, " +
                    "internship_id NUMBER, " +
                    "company_id NUMBER, " +
                    "student_name VARCHAR2(200), " +
                    "company_name VARCHAR2(200), " +
                    "role_title VARCHAR2(200), " +
                    "test_score NUMBER(5,2), " +
                    "proctor_warnings NUMBER(4) DEFAULT 0, " +
                    "status VARCHAR2(50) DEFAULT 'APPLIED', " +
                    "stage VARCHAR2(50) DEFAULT 'ASSESSMENT', " +
                    "applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
        } catch (Exception e) {}

        try {
            // Seed standard live internships if none exist
            int count = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM internships", Integer.class);
            if (count == 0) {
                jdbcTemplate.update("INSERT INTO internships (company_id, company_name, title, domain, required_skills, work_mode, grad_year, location, duration, start_date, end_date, stipend, openings, application_deadline, status) VALUES " +
                        "(10, 'NVIDIA Corporation', 'AI/ML Engineering Intern', 'Artificial Intelligence', 'Python, PyTorch, CUDA, Algorithms', 'Hybrid', 2026, 'Bengaluru', '3 Months', '2026-06-01', '2026-08-31', 45000, 5, '2026-07-30', 'ACTIVE')");

                jdbcTemplate.update("INSERT INTO internships (company_id, company_name, title, domain, required_skills, work_mode, grad_year, location, duration, start_date, end_date, stipend, openings, application_deadline, status) VALUES " +
                        "(11, 'Google Cloud Labs', 'Full-Stack Software Engineering Intern', 'Cloud & Web Systems', 'React, Java, Spring Boot, SQL', 'Remote', 2026, 'Hyderabad', '6 Months', '2026-06-01', '2026-11-30', 40000, 4, '2026-08-15', 'ACTIVE')");
            }
        } catch (Exception e) {}
    }
}
